name: 'Slack CI Notifications'
description: 'Slack notifications for GitHub Actions CI workflows.'
author: 'Princeton-CDH'
inputs:
  webhook:
    required: true
    description: 'Slack webhook URL for posting notifications'
  channel:
    required: false
    description: 'Slack channel to post in; leave blank to use webhook default'
runs:
  using: 'node12'
  main: 'dist/main.js'
branding:
  icon: 'hash'
  color: 'white'
